version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      TYPEORM_CONNECTION: postgres
      TYPEORM_HOST: db
      TYPEORM_PORT: 5432
      TYPEORM_USERNAME: myuser
      TYPEORM_PASSWORD: mypassword
      TYPEORM_DATABASE: mydatabase
      TYPEORM_SYNCHRONIZE: 'true'

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '8080:80'

  adminer:
    image: adminer
    ports:
      - "8081:8080"
    environment:
      - ADMINER_DESIGN=hydra
    depends_on:
      - db
    
volumes:
  db_data:
